image: debian:stretch-backports

# NOTE: ASan doesn't work on Gitlab runners, each commit has to be checked locally.

stages:
  - test
  - coverity

before_script:
  - apt update
  - apt install -y -t stretch-backports build-essential meson clang-tools-6.0 libfuzzer-6.0-dev libubsan0 zlib1g-dev libpng-dev python3-pkgconfig gcovr wget tar curl

test:
  stage: test
  script:
    - CC=clang-6.0 CXX=clang++-6.0 meson -Ddev_build=true -Db_sanitize=undefined -Db_lundef=false clang_build
    - ninja -C clang_build scan-build
    - ninja -C clang_build
    - CC=gcc CXX=g++ meson -Ddev_build=true -Db_sanitize=undefined -Db_coverage=true gcc_build
    - cd gcc_build
    - ninja
    - meson test info -v
    - ninja test
    - ninja coverage-text
    - cat meson-logs/coverage.txt
    - cd ..
    - bash <(curl -s https://codecov.io/bash)
  artifacts:
    paths:
      - clang_build/
      - gcc_build/

coverity:
  stage: coverity
  when: manual
  script:
    - wget https://scan.coverity.com/download/linux64 --post-data "token=$COVERITY_TOKEN&project=randy408%2Flibspng" -O coverity_tool.tgz
    - mkdir coverity_tool
    - tar -xvzf coverity_tool.tgz -C coverity_tool --strip-components=1
    - ninja -C gcc_build clean
    - ./coverity_tool/bin/cov-build --dir cov-int ninja -C gcc_build
    - tar czvf spng.tgz cov-int
    - curl --form token=$COVERITY_TOKEN --form email=randy408@protonmail.com --form file=@spng.tgz --form version="master" --form description="libspng" https://scan.coverity.com/builds?project=randy408%2Flibspng
    - rm spng.tgz
    - rm -r cov-int
