# .circleci/config.yml
version: 2.1

jobs:
  test-arm:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: uname -a
      - run: echo "Hello, Arm!"
      - run: sudo apt install meson git-lfs ninja-build
      - run: meson -Ddev_build=true build
      - run: cd build
      - run: ninja test

workflows:
  build:
    jobs:
      - test-arm